language: python

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIAXHPVLDE6LUSZFCWC"
  secret_access_key:
    secure: "tkGsysVrEyDD6ChdMjTQXOSUQtdcm8HSQxb78S4p"
  region: "us-east-1"
  app: "swe1-app"
  env: "example-app-environment"
  bucket_name: "swe1-app-bucket"
  
only_create_app_version: "true"
