language: python

python:
  - 3.8

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  
before_script:
  - python manage.py migrate

script:
  - python -m black . --check
  - python -m flake8 --ignore=E303,E501 --max-line-length=88
  - python -m coverage run manage.py test 
  #- flake8 --extend-ignore E203,E501,E401

after_success:
  coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIATIOYYKGRB54H7ZEL"
  secret_access_key: "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"
  region: "us-west-2"
  app: "swe1-app"
  env: "django-test1"
  bucket_name: "elasticbeanstalk-us-west-2-224329748898"
  on:
      repo: Pankhurinyu/swe1-app
      branch: main





