language: python

python:
  - 3.8

install:
  - pip install -r requirements.txt
  
script:
  - black ./
  - flake ./
  - coveralls ./
  - python manage.py test

after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIAXHPVLDE6LUSZFCWC"
  secret_access_key: "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"
  region: "us-west-2"
  app: "swe1-app"
  env: "django-test1"
  bucket_name: "elasticbeanstalk-us-west-2-497120123196"
  on:
      repo: Pankhurinyu/swe1-app/mysite
      branch: main
